import MojoBindingCore

package struct MojoStaticRegistryWriter: Sendable {
    package static let generationVersion = 2

    package init() {}

    package func source(
        manifest: MojoArtifactManifest,
        inputGraph: MojoInputGraph
    ) -> String {
        let bindingIDs = inputGraph.bindingGraph.bindings
            .map { String($0.bindingID) }
            .joined(separator: ", ")
        let identity = manifest.effectiveIdentity
        let prefix = identity.symbolPrefix
        let conditions = Set(
            manifest.effectiveSlices.compactMap {
                Self.swiftCondition(for: $0.target.triple)
            }
        ).sorted().joined(separator: " || ")
        let platformGuard = conditions.isEmpty
            ? "#error(\"The prepared Mojo artifact has no Swift-compatible Apple slice\")"
            : "#if \(conditions)\n#else\n#error(\"The prepared Mojo artifact does not support this Swift destination\")\n#endif"
        let expectedInputGraph = manifest.inputGraphIdentifier
            ?? manifest.sourceGraphIdentifier
        let graphFunction = manifest.schemaVersion
            == MojoArtifactManifest.legacySchemaVersion
            ? "\(prefix)_source_graph_identifier"
            : "\(prefix)_input_graph_identifier"
        return """
        // Generated by swift-mojo. Do not edit.
        // Artifact SHA-256: \(manifest.artifactDigest)
        // Generation pipeline SHA-256: \(manifest.generationPipelineDigest)
        import \(identity.moduleName)

        \(platformGuard)

        enum __SwiftMojoGeneratedBindings {
            private static let expectedABIVersion: UInt32 = \(manifest.abiVersion)
            private static let expectedInputGraph: UInt64 = \(expectedInputGraph)
            private static let preparedBindingIDs: Set<UInt64> = [\(bindingIDs)]

            @inline(__always)
            static func invokeInt32Binary(
                bindingID: UInt64,
                lhs: Int32,
                rhs: Int32
            ) -> Int32 {
                guard \(prefix)_static_abi_version() == expectedABIVersion else {
                    fatalError("The linked Mojo artifact has an incompatible static ABI")
                }
                guard \(graphFunction)() == expectedInputGraph else {
                    fatalError("The linked Mojo artifact does not match the prepared input graph")
                }
                guard preparedBindingIDs.contains(bindingID),
                      \(prefix)_has_binding(bindingID) == 1 else {
                    fatalError("The linked Mojo artifact does not contain the requested binding")
                }
                return \(prefix)_call_i32_i32_i32(bindingID, lhs, rhs)
            }
        }
        """ + "\n"
    }

    private static func swiftCondition(for triple: String) -> String? {
        let normalized = triple.lowercased()
        let architecture: String
        if normalized.hasPrefix("arm64-") || normalized.hasPrefix("aarch64-") {
            architecture = "arm64"
        } else if normalized.hasPrefix("x86_64-") {
            architecture = "x86_64"
        } else {
            return nil
        }

        let operatingSystem: String
        if normalized.contains("-apple-macos") {
            operatingSystem = "macOS"
        } else if normalized.contains("-apple-ios") {
            operatingSystem = "iOS"
        } else {
            return nil
        }
        return "(arch(\(architecture)) && os(\(operatingSystem)))"
    }
}
