import MojoBindingCore

package struct MojoStaticRegistryWriter: Sendable {
    package static let generationVersion = 1

    package init() {}

    package func source(
        manifest: MojoArtifactManifest,
        graph: MojoSourceGraph
    ) -> String {
        let bindingIDs = graph.bindings.map { String($0.bindingID) }
            .joined(separator: ", ")
        return """
        // Generated by swift-mojo. Do not edit.
        // Artifact SHA-256: \(manifest.artifactDigest)
        // Generation pipeline SHA-256: \(manifest.generationPipelineDigest)
        import GeneratedMojoABI

        #if arch(arm64) && os(macOS)
        #else
        #error("The prepared Mojo artifact supports only arm64 macOS")
        #endif

        enum __SwiftMojoGeneratedBindings {
            private static let expectedABIVersion: UInt32 = \(manifest.abiVersion)
            private static let expectedSourceGraph: UInt64 = \(manifest.sourceGraphIdentifier)
            private static let preparedBindingIDs: Set<UInt64> = [\(bindingIDs)]

            @inline(__always)
            static func invokeInt32Binary(
                bindingID: UInt64,
                lhs: Int32,
                rhs: Int32
            ) -> Int32 {
                guard swift_mojo_static_abi_version() == expectedABIVersion else {
                    fatalError("The linked Mojo artifact has an incompatible static ABI")
                }
                guard swift_mojo_source_graph_identifier() == expectedSourceGraph else {
                    fatalError("The linked Mojo artifact does not match the prepared source graph")
                }
                guard preparedBindingIDs.contains(bindingID),
                      swift_mojo_has_binding(bindingID) == 1 else {
                    fatalError("The linked Mojo artifact does not contain the requested binding")
                }
                return swift_mojo_call_i32_i32_i32(bindingID, lhs, rhs)
            }
        }
        """ + "\n"
    }
}
